import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { htmlFileFor, pages } from './src/data/pages.js'

// Multi-page build: one HTML entry per page (generated by scripts/generate-pages.mjs).
// User/organization Pages (username.github.io) serves from repo root — keep base '/'.
export default defineConfig({
  plugins: [react()],
  base: '/',
  build: {
    rollupOptions: {
      input: Object.fromEntries(pages.map((page) => [htmlFileFor(page), resolve(import.meta.dirname, htmlFileFor(page))])),
    },
  },
})
