// Writes one HTML entry file per page in src/data/pages.js (index.html, projects/index.html, ...).
// Runs before `vite` and `vite build`; the generated files are gitignored.
import { mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { htmlFileFor, pages } from '../src/data/pages.js'
import { siteConfig } from '../src/siteConfig.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = join(root, '.generated-pages.json')

const escape = (value) =>
  String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

const jsonLd = JSON.stringify({
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: siteConfig.name,
  url: siteConfig.siteUrl,
  image: `${siteConfig.siteUrl}${siteConfig.headshotUrl}`,
  jobTitle: siteConfig.title,
  sameAs: [siteConfig.githubUrl, siteConfig.linkedinUrl],
  alumniOf: { '@type': 'CollegeOrUniversity', name: 'Brigham Young University' },
})

function render(page) {
  const url = `${siteConfig.siteUrl}${page.path === '/404.html' ? '/' : page.path}`
  const title = escape(page.title)
  const description = escape(page.description)
  const ogImage = `${siteConfig.siteUrl}/og-card.png`

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- Generated by scripts/generate-pages.mjs from src/data/pages.js. Edit those, not this file. -->
    <script>
      (function () {
        var t = null
        try {
          t = localStorage.getItem('theme')
        } catch (e) {}
        if (t === 'dark' || (t !== 'light' && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark')
        }
      })()
    </script>
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <meta name="description" content="${description}" />
    <meta name="author" content="${escape(siteConfig.name)}" />${
      page.noindex ? '\n    <meta name="robots" content="noindex" />' : `\n    <link rel="canonical" href="${url}" />`
    }

    <meta property="og:type" content="website" />
    <meta property="og:url" content="${url}" />
    <meta property="og:site_name" content="${escape(siteConfig.name)}" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="${escape(siteConfig.name)} — ${escape(siteConfig.title)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />
    <meta name="twitter:image" content="${ogImage}" />
${page.page === 'home' ? `    <script type="application/ld+json">${jsonLd}</script>\n` : ''}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:ital,opsz,wght@0,8..60,600;1,8..60,600&display=swap"
      rel="stylesheet"
    />
  </head>
  <body data-page="${page.page}"${page.slug ? ` data-slug="${escape(page.slug)}"` : ''}>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`
}

// Remove files from the previous run so renamed or deleted pages don't linger.
if (existsSync(manifestPath)) {
  for (const file of JSON.parse(readFileSync(manifestPath, 'utf8'))) {
    rmSync(join(root, file), { force: true })
  }
}

const written = []
for (const page of pages) {
  const file = htmlFileFor(page)
  mkdirSync(dirname(join(root, file)), { recursive: true })
  writeFileSync(join(root, file), render(page))
  written.push(file)
}
writeFileSync(manifestPath, JSON.stringify(written, null, 2) + '\n')
console.log(`Generated ${written.length} pages`)
